apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bss

resources:
  - ../../base

images:
  - name: customer-service
    newName: CHANGE_ME.dkr.ecr.ap-southeast-1.amazonaws.com/bss/customer-service
    newTag: v0.0.0

configMapGenerator:
  - name: customer-service-config
    literals:
      - SPRING_PROFILES_ACTIVE=aws
      - LOG_LEVEL=INFO
      - AWS_REGION=ap-southeast-1
      - DB_NAME=customer

replicas:
  - name: customer-service
    count: 3

# Production-only patches: tighter resources, stricter PDB.
patches:
  - target:
      kind: ServiceAccount
      name: customer-service
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: arn:aws:iam::CHANGE_ME_ACCOUNT_ID:role/bss-prod-customer-service

  - target:
      kind: Ingress
      name: bss-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: bss.example.com
      - op: add
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: bss.example.com

  - target:
      kind: PodDisruptionBudget
      name: customer-service
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 2 # tighter in prod

  - target:
      kind: Deployment
      name: customer-service
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "768Mi"
