apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-ingress.yaml
  - allow-monitoring-scrape.yaml
  - allow-public-ingress.yaml
  - allow-gateway-to-backends.yaml
