apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bss

resources:
  - customer-db-credentials-spc.yaml
  - product-db-credentials-spc.yaml
  - order-db-credentials-spc.yaml
  - billing-db-credentials-spc.yaml
